### ISSUE TITLE
JAR files (ZIP format with .jar extension)

### ISSUE THREAD

**Issue by guillaume-uH57J9** [xlmnxp/extractify.zip#9]
Consider adding basic support for .jar files. This should be relatively easy as [the jar format is based on the zip format](https://en.wikipedia.org/wiki/JAR_(file_format)), so extractify could interpret jars exactly the same way as zips. 

Loading a Jar file in extractify.zip fails because the .jar extension is not recognized. But renaming the file to change the  extension to .zip and trying again allows browsing the file's content.

**Comment by xlmnxp** [comment]
done :)
thank you for reporting
